########################################################################
# Copyright (c) 1988-2020 $organization$
#
# This software is provided by the author and contributors ``as is''
# and any express or implied warranties, including, but not limited to,
# the implied warranties of merchantability and fitness for a particular
# purpose are disclaimed. In no event shall the author or contributors
# be liable for any direct, indirect, incidental, special, exemplary,
# or consequential damages (including, but not limited to, procurement
# of substitute goods or services; loss of use, data, or profits; or
# business interruption) however caused and on any theory of liability,
# whether in contract, strict liability, or tort (including negligence
# or otherwise) arising in any way out of the use of this software,
# even if advised of the possibility of such damage.
#
#   File: Makefile
#
# Author: $author$
#   Date: 3/26/2020
#
# generic Gcc Makefile for nadir Library libnadir
########################################################################


#
# target
#
libnadir_LIBTARGET = libnadir.${LIBEXT}

########################################################################

#
# user c++ flags
#
libnadir_USRCXXFLAGS += \
${nadir_USRCXXFLAGS} \

#
# user defines
#
libnadir_USRDEFINES += \
${nadir_USRDEFINES} \

#
# user includes
#
libnadir_USRINCLUDES += \
${nadir_USRINCLUDES} \

#
# user libdirs
#
libnadir_USRLIBDIRS += \
${nadir_USRLIBDIRS} \

########################################################################

#
# Library .c sources
#
#libnadir_LIB_C_SOURCES += \
#${NADIR_SRC}/nadir/base/Base.c \

#
# Library .cc sources
#
#libnadir_LIB_CC_SOURCES += \
#${NADIR_SRC}/nadir/base/Base.cc \

#
# Library .cxx sources
#
#libnadir_LIB_CXX_SOURCES += \
#${NADIR_SRC}/nadir/base/Base.cxx \

#
# Library .cpp sources
#
libnadir_LIB_CPP_SOURCES += \
${NADIR_SRC}/xos/lib/nadir/version.cpp \

#
# Library .m sources
#
#libnadir_LIB_M_SOURCES += \
#${NADIR_SRC}/nadir/base/Base.m \

#
# Library .mm sources
#
#libnadir_LIB_MM_SOURCES += \
#${NADIR_SRC}/nadir/base/Base.mm \


########################################################################




